# Generated by Django 5.1.15 on 2026-06-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0009_todooccurrence_is_low_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todooccurrence",
            name="location_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="todooccurrence",
            name="location_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="todooccurrence",
            name="location_name",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
        migrations.AddField(
            model_name="todooccurrence",
            name="location_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
