# Generated by Django 5.1.15 on 2026-07-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0012_task_is_archived_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todooccurrence",
            name="location_radius_meters",
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name="todooccurrence",
            name="location_reminder_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
