# Generated by Django 5.1.15 on 2026-06-30 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilityRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("step_count", models.PositiveIntegerField(default=0)),
                ("distance_meters", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_id", models.CharField(max_length=120)),
                ("recorded_at", models.DateTimeField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("heading", models.FloatField(blank=True, null=True)),
                ("place_name", models.CharField(blank=True, default="", max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="mobility.mobilityrecording",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="StepSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=100)),
                ("step_count", models.PositiveIntegerField(default=0)),
                ("recorded_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_samples",
                        to="mobility.mobilityrecording",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mobilityrecording",
            index=models.Index(fields=["user", "started_at"], name="mobility_rec_user_started_idx"),
        ),
        migrations.AddConstraint(
            model_name="mobilityrecording",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="uniq_active_mobility_recording",
            ),
        ),
        migrations.AddIndex(
            model_name="locationpoint",
            index=models.Index(
                fields=["recording", "recorded_at"], name="mobility_point_rec_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationpoint",
            constraint=models.UniqueConstraint(
                fields=("recording", "client_id"), name="uniq_location_point_client_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="stepsample",
            constraint=models.UniqueConstraint(
                fields=("recording", "source_id"), name="uniq_step_sample_source"
            ),
        ),
    ]
