# Generated by Django 5.1.15 on 2026-07-04 10:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(max_length=120)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("app_foreground", "App foreground"),
                            ("screen_on", "Screen on"),
                            ("screen_off", "Screen off"),
                            ("unlock", "Unlock"),
                            ("shutdown", "Shutdown"),
                            ("boot", "Boot"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "package_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("app_label", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="device_tl_user_occurred_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_id"),
                        name="uniq_device_timeline_event_client_id",
                    )
                ],
            },
        ),
    ]
