# Generated by Codex on 2026-07-01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientLogEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_id", models.CharField(max_length=80)),
                ("session_id", models.CharField(max_length=80)),
                ("device_id", models.CharField(blank=True, max_length=80)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warn", "Warn"),
                            ("error", "Error"),
                            ("fatal", "Fatal"),
                        ],
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=80)),
                ("message", models.TextField()),
                ("stack", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField()),
                ("app_version", models.CharField(blank=True, max_length=40)),
                ("build_sha", models.CharField(blank=True, max_length=80)),
                ("platform", models.CharField(blank=True, max_length=32)),
                ("os_version", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clientlogentry",
            index=models.Index(fields=["user", "-occurred_at"], name="diag_log_user_time_idx"),
        ),
        migrations.AddIndex(
            model_name="clientlogentry",
            index=models.Index(fields=["level", "-occurred_at"], name="diag_log_level_time_idx"),
        ),
        migrations.AddIndex(
            model_name="clientlogentry",
            index=models.Index(fields=["session_id"], name="diag_log_session_idx"),
        ),
        migrations.AddConstraint(
            model_name="clientlogentry",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"),
                name="uniq_client_log_user_client_id",
            ),
        ),
    ]
